server:
  port: 9093

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata_test
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lqh.domain

mapper:
  mappers:
    - com.lqh.mybatis.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000